# Generated by Django 4.1 on 2022-12-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customtoken_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("LOGISTICS", "Logistics"), ("NSH", "Nsh"), ("NLH", "Nlh")],
                default="NSH",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CustomToken",
        ),
    ]
